language: node_js
node_js:
  - 14
cache:
  yarn: true
  directories:
    - public
    - .cache
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  target_branch: gh-pages
  on:
    branch: main